---
# tasks file for doa.docker
- name: Ensure old Docker Packages are uninstalled and update cache
  apt:
    name: "{{item}}"
    state: absent
    update_cache: yes
  with_items:
    - docker
    - docker-engine
    - docker.io
  become: true

- name: Install apt https transport support
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  become: true

- name: Install Docker's official apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
    state: present
  become: true
# you can get the short key id with this command
# curl -sSL https://download.docker.com/linux/ubuntu/gpg | gpg --import-options show-only --keyid-format SHORT -

- name: Add Docker's apt repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
  become: true

- name: update apt cache and get official docker
  apt:
    name: "{{ docker_package_name + '=' + docker_package_version }}"
    update_cache: yes
    state: present
  become: true